### ISSUE TITLE
Does it support x/y coordinates on where I want to display the overlay?

### ISSUE THREAD

**Issue by sanakanchha** [videojs/videojs-overlay#111]
## Description
Briefly describe the issue.
Include a [reduced test case](https://css-tricks.com/reduced-test-cases/).

Lets say I want to display a (html)table at 3:14 seconds of a video at 10 px from both the top and the left. 

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1.
2.
3.

### Expected
Please describe what you expected to see.

### Actual
Please describe what actually happened.

### Error output
If there are any errors at all, please include them here.

## Additional Information
Please include any additional information necessary here. Including the following:

#### videojs
what version of videojs does this occur with?

#### browsers
what browser are affected?

#### OSes
what platforms (operating systems and devices) are affected?

### plugins
are any videojs plugins being used on the page? If so, please list them below.

**Comment by gkatsev** [comment]
I believe the only positioning stuff right now is align: https://github.com/brightcove/videojs-overlay#align.
Generally, you'd want to add a class to the overlays and position it with CSS.
